name: stargan-v2
channels:
  - pytorch
  - conda-forge
  - defaults
dependencies:
  - pip=20.2.4
  - python=3.6
  - pytorch=1.7.0
  - torchvision=0.8.0
  - cudatoolkit=11.0
  - x264=1!152.20180717
  - ffmpeg=4.0.2
  - pip:
    - opencv-python==4.1.2.30 
    - ffmpeg-python==0.2.0
    - scikit-image==0.16.2
    - pillow==7.0.0 
    - scipy==1.2.1
    - tqdm==4.43.0
    - munch==2.5.0
    - Flask==1.1.2
    - sqlalchemy==1.3.22
    - flask-restful==0.3.8
    - Flask-SQLAlchemy==2.4.4
    - flask-marshmallow==0.14.0
    - marshmallow-sqlalchemy==0.24.1
